// This file is generated by Slice Machine. Update with care!

import Accordion from './Accordion';
import Image from './Image';
import Text from './Text';

export {
	Accordion,
	Image,
	Text,
};

export const components = {
	accordion: Accordion,
	image: Image,
	text: Text,
};
